version: '3.4'

services:
  sqldata:
    environment:
      - SA_PASSWORD=test@1234
      - ACCEPT_EULA=Y
    ports:
      - "1433:1433"
  ocelotapigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  resourceapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  identityapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
  #consul:
   # ports:
   #   - "8500"
